### ISSUE TITLE
Cannot get this plugin to work.

### ISSUE THREAD

**Issue by tehloxely** [nurupo/vlc-pause-click-plugin#41]
I am using VLC v3.0.2 (64bit) for Win10 and I cannot get the plugin to work. I've even tried all the troubleshooting advice on the README.

**Comment by nurupo** [comment]
How far did you get? Do you see the plugin in the Preferences or you didn't get that far?

Also, make sure that the VLC you use is indeed 64-bit VLC and not 32-bit, because [the default VLC download](https://www.videolan.org/vlc/download-windows.html) is 32-bit, to get the 64-bit one you must go out of your way to click on the drop down options.

If you use 32-bit VLC, the plugin goes into `C:\Program Files (x86)\VideoLAN\VLC\plugins\`, if  you use 64-bit VLC the plugin goes into `C:\Program Files (x86)\VideoLAN\VLC\plugins\`. If you have both of those directories then you have both 32-bit and 64-bit VLC installed, figure out which one of those you actually use and put the appropriate plugin .dll into there, or just put them in both.

**Comment by tehloxely** [comment]
I tried 3 more times and it finally showed up in the options. I honestly don't know why it wouldn't show up.

**Comment by tehloxely** [comment]
I tried 3 more times and it finally showed up in the options. I honestly don't know why it wouldn't show up.
