### ISSUE TITLE
Loss of play/pause click functionality with h.265/h.264 codecs

### ISSUE THREAD

**Issue by ThaddeusChristopher** [nurupo/vlc-pause-click-plugin#45]
I'm on VLC 3.0.4 64-bit Windows and believe I may be experiencing loss of plugin functionality (if not, then I apologize ahead of time).

The following checkboxes are checked as per the instructions:

- Video >> Filters >> Pause/Play video on mouse click (text box reads "postproc:pause_click", also tested with just "pause_click")
- Interface >> Control interfaces >> Pause/Play video on mouse click (text box reads "pause_click")
Left mouse clicks are no-ops with or without "Ignore double clicks".

In VLC's Advanced Preferences, if I check "Only show current" it does indeed display "Pause click" as a sub-node under Filters.

Restarting VLC (with or without using the --reset-plugins-cache option) does not appear to help. Starting VLC with or without admin privileges also does not appear to change matters. Non-left-click variants (e.g., middle click) have also yielded no joy.

**Comment by nurupo** [comment]
I assume you meant that you use 64-bit VLC. Will try reproducing in a clean Windows 10 64-bit VM right with 64-bit VLC 3.0.4 and will report back.

**Comment by nurupo** [comment]
Just tested and it works. [Here is a video](https://a.doko.moe/owoydu.webm), though you can't see the mouse cursor or mouse presses.

The fact that you see the plugin checkboxes means that you got the correct plugin for your VLC version and bitness, otherwise the plugin wouldn't even load. You have also checked all 2 of the required checkboxes, so the plugin must be enabled. Not sure why it doesn't work for you.

Just to make sure, you are testing the plugin on a video file, right? The plugin is a video filter plugin, so it works only when clicking on a video image, if you, for example, play an audio-only file and try to click anywhere in VLC - the plugin won't pause/unpause anything as there is no video surface for you to click on. The plugin can only detect mouse clicks done on video images.

**Comment by ThaddeusChristopher** [comment]
Thank you for your time and hard work. 

I have made some progress in discovering the root cause of this case.

I had only been testing with .mp4 and .mkv, using only containers with subtitles and encoded with the HEVC codec. These files continue to not allow click-based pause/play functionality. 

However, any ordinary .avi or .wmv appears to work as expected.

For convenience, an example test file which is able to reproduce this case can be found here: http://jell.yfish.us/ (jellyfish-3-mbps-hd-hevc.mkv)

**Comment by nurupo** [comment]
The only thing that would make sense is that when playing h.265 VLC for some reason doesn't send mouse events to plugins. If so, it needs to be fixed in VLC, nothing I can do in the plugin about that.

Btw, the plugin works just fine with h264 for me, at least with `Codec: H264 - MPEG-4 AVC (part 10) (avc1)`, so it might be just h265.

**Comment by nurupo** [comment]
I have tried the following files:

- `jellyfish-3-mbps-hd-hevc.mkv`
- `jellyfish-3-mbps-hd-hevc-10bit.mkv`
- `jellyfish-3-mbps-hd-h264.mkv`

The plugin works on all of them, at least under Linux on VLC 3.0.3. Will try testing on Windows sometime later.

**Comment by nurupo** [comment]
>Btw, the plugin works just fine with h264 for me, at least with Codec: H264 - MPEG-4 AVC (part 10) (avc1), so it might be just h265.

That was on Linux too. For a moment I forgot the issue was about Windows.

**Comment by nurupo** [comment]
>The plugin works on all of them, at least under Linux on VLC 3.0.3. Will try testing on Windows sometime later.

Tested on Windows 10 64-bit using 64-bit VLC 3.0.4 -- same thing, the plugin works on all three of the mentioned video files.

**Comment by ThaddeusChristopher** [comment]
The last thing I can think of that could be causing this is DirectVobSub (which shows as a green arrow in the System Tray). It is displaying in the System Tray on every file that does not work with the play/pause plugin.

I had assumed it was a natural part of VLC, but no doubt it may have come from a codec pack (would have been CCCP in my case). Let's see if I'm able to fully remove it for testing purposes...

**Comment by ThaddeusChristopher** [comment]
Chalking this one up to an unknown plugin conflict.

During a process of uninstalling & installing various prior VLC builds, 2.2.x and 3.0.x, 32-bit and 64-bit, I eventually reinstalled VLC 3.0.4 with option to "Delete preferences and cache" checked, and this plugin is now a happy camper :-)

Unfortunately I did not backup my previous plugin settings and preferences which could have allowed further root cause investigation.

**Comment by nurupo** [comment]
Added 

>Some users have reported that they had to re-install VLC and select "Delete preferences and cache" in the installer for the plugin to work.

into the README.
