### ISSUE TITLE
Play nicely with double click

### ISSUE THREAD

**Issue by akamustang** [nurupo/vlc-pause-click-plugin#5]
Double click is a shortcut to fullscreen, would be good if this could be detected and the video wasn't played/paused in this instance.

A possible implementation would be to delay the play/pause until after the double click time window has expired, and then trigger if it was a single click only.

**Comment by eslachance** [comment]
This is the same behaviour that MPC-HC exhibits on double-click. Not sure I'd want it to change, since that would mean that pausing would take a second or so...

**Comment by blole** [comment]
I'd propose doing it the same way youtube does it, which I think is something like:
When clicked, wait with pausing for ~150ms, if the user clicks again within that time, then just fullscreen, otherwise pause but if the user then clicks within his operating system defined double-click speed time, fullscreen and unpause.

**Comment by ahsanshami** [comment]
Figuring this out would be great. Right now, it amounts to a double + single click to fullscreen a playing video. I figured that I'd get used to it, but it's been about 10 days and I still get tripped up daily.

It working the way everything else works would be fantastic.

Thanks.

**Comment by nurupo** [comment]
I'm pretty happy with the current plugin behaviour, also the double click handling is so complex in comparison to what the plugin does now, that I don't see myself implementing this feature I don't even need myself. Note that this plugin was written primarily for myself, I simply decided to share it. However, if someone wants to implement it, I will consider their pull request.

A possible implementation of this would be

```
on mouse click:
    if the last recorded mouse click was long before 150ms ago
        this is a single click -- record current mouse click time in milliseconds
        spawn a thread (so that we won't block the execution flow)
            in the new thread, sleep for 150ms
            if no second mouse click occurred after the sleep is over
                it was just a single click -- pause the video
            else
                the user must have double clicked -- don't pause the video
    else
        the user must have double clicked -- don't pause the video
```

(150ms is just an arbitrary number, it might be too large or small for double click detection)

There are all sorts of issues with this. First, you need a cross-platform sleep function and link to platform-specific libraries providing it. Second, you need to spawn a thread, so you would need to link the plugin against some (cross-platform?) threading library (pthread?), adding a new dependency. Third, you will have to call VLC function from a different thread. Are VLC functions thread safe? If not, then you can't do that and the whole feature implementation falls to pieces. Fourth, you'd need some synchronization primitives like mutex (provided by pthread library), or an atomic 64 bit integer, to prevent possible race conditions of accessing the recorded mouse click time.

If you are going to implement this feature, don't forget to make it cross-platform, take care of thread-safety if you are going to use threads and update the building.md with platform-depended build information.

**Comment by fonaro** [comment]
It can be simply solved by using the middle button instead of the left.
I've send a pull request implementing a settings menu to select which mouse button pause/play the video. Please consider it.

**Comment by nurupo** [comment]
>I'm pretty happy with the current plugin behaviour

I have recently used the plugin on Windows and realized that I'm actually not that happy with the double-click behaviour.

I use VLC mostly on Linux, and VLC handles double-click differently on Linux and Windows.

On Linux, you always end up in the same state (either playing or paused) after double clicking that you were in before the double clicking. It goes like this:
```
first click -> play/pause -> second click -> pause/play
```

On Windows, however, you end up in the opposite state after double clicking that you were in before the double clicking. It goes like this:
```
first click -> play/pause -> second click -> nothing changes
```

I will try to make the plugin on Windows match its behaviour from Linux.

I have a fix for this already, just need to test it, organize things and push it.

This doesn't mean that the video won't be playing/pausing in between the double clicks, it will continue doing that, so that issue is not being addressed by the fix I mentioned.

**Comment by nurupo** [comment]
As a workaround, you can use a middle mouse key (the wheel) to trigger pause/play, with double-clicking left mouse button (e.g. to full screen) not triggering pause/play.

**Comment by nurupo** [comment]
>Figuring this out would be great. Right now, it amounts to a double + single click to fullscreen a playing video.

@ahsanshami Forgot to give you heads up that the fix for your issue, the one that I have mentioned in https://github.com/nurupo/vlc-pause-click-plugin/issues/5#issuecomment-192786945, was added in version 0.3,0 on March 6th 2016.

**Comment by nurupo** [comment]
I'm playing around with a new feature that lets the plugin ignore double clicks. Turns out it was easier to do that I have though, didn't know VLC already provided atomics, threads and timers.

I would like you to test this new feature and provide feedback, if you have any. The code change is in a separate branch for now, at https://github.com/nurupo/vlc-pause-click-plugin/tree/ignore-double-click. Here are Windows builds
 
[vlc-2.1.x-32bit-win.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/1484648/vlc-2.1.x-32bit-win.zip)
[vlc-2.1.x-64bit-win.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/1484649/vlc-2.1.x-64bit-win.zip)
[vlc-2.2.x-32bit-win.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/1484650/vlc-2.2.x-32bit-win.zip)
[vlc-2.2.x-64bit-win.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/1484651/vlc-2.2.x-64bit-win.zip)

You can find a couple new options available at `Video -> Filters -> Pause click`
1. An option to enable/disable ignoring of double clicks. It's enabled by default in these test builds.
2. Double click time interval, I have set it to 300ms by default as this is what worked the best for me. You can change the value to anything in-between 20ms and 5000ms.

I'm leaning towards having this double click feature disabled by default in the release builds (you would be able to enable it in settings), as the 300ms "input lag" annoys me a lot. The way the new feature works: you click for the first time, it starts waiting for 300ms for a possible second click, and if you haven't clicked within those 300ms again, it will pause/play the video. However, if you click within the 300ms, it would count that as a double click and it would ignore both clicks. So there is this 300ms delay between the click and pausing/playing. I'd like a feedback on how you feel about this delay.

**Comment by blole** [comment]
Nice! 😃
I tested the timing with autohotkey and when setting the `double click interval` to 200 ms, VLC seems to behave exactly like youtube. With that value I don't think it's lagging enough to be annoying.

**Comment by nurupo** [comment]
It looks like VLC full-screens if you double-click within 300ms, at least that's the case with the Qt interface of VLC on KDE Linux (doesn't VLC on macOS use some different interface?). The way to check this is to set the double-click interval in the plugin to 275ms, then click once and as soon as the video pauses (i.e. 275ms has elapsed) click again. If you manage to get the video to pause and then play while also full-screening, it means that the double-click interval is shorter than (or equal to) the full-screen interval used by VLC, assuming the precision error of the timer the plugin uses is negligible.

**Comment by nurupo** [comment]
This issue should be resolved with the 0.4.0 release that was just made.

**Comment by akamustang** [comment]
Excellent news, very excited to see this land.

I'm actually having to run VLC 3.0 due to am unrelated bug in 2.2. Doh!

But I look forward to being able to use your plugin again soon.

Thanks!

**Comment by nurupo** [comment]
VLC 3.0 is not released yet though, you are running a nightly version. The issue with the nightly version is that it keeps changing, so the plugin built for it at one point of time might stop working with a newer nightly version of it, which is something that has happened to someone (there was an issue about this created). I will start supporting VLC 3.0 once it's actually released.
