### ISSUE TITLE
Right click Menu

### ISSUE THREAD

**Issue by gKrager** [nurupo/vlc-pause-click-plugin#55]
I just added this plugin to my VLC, only problem is I like having the Right Click as my "play/pause" and while it does work, the menu that is displayed by default with the right click still opens. Is there a way of disabling said menu?

Thanks!

**Comment by nurupo** [comment]
That's interesting, never expected anyone to actually use the Right Button option. I have added those button choices just because I could and having an option to use Middle Button sounded nice.

Anyway, I can modify the plugin to prevent the context menu from appearing. I wouldn't be able to properly test it for about a week though, don't have a Windows machine nearby, so releasing this change will have to wait. Meanwhile you can test it yourself. I have pushed the code to [`suppress-context-menu`](https://github.com/nurupo/vlc-pause-click-plugin/tree/suppress-context-menu) branch in case you compile from source, and here are Windows binaries:

- [vlc-2.1-32bit-win.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/3048265/vlc-2.1-32bit-win.zip)
- [vlc-2.1-64bit-win.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/3048266/vlc-2.1-64bit-win.zip)
- [vlc-2.2-32bit-win.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/3048267/vlc-2.2-32bit-win.zip)
- [vlc-2.2-64bit-win.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/3048268/vlc-2.2-64bit-win.zip)
- [vlc-3.0-32bit-win.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/3048269/vlc-3.0-32bit-win.zip)
- [vlc-3.0-64bit-win.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/3048270/vlc-3.0-64bit-win.zip)

By the way, if you are using Right Button instead of Left Button because you don't like the video pausing and then playing when you double-click to full screen - there is an option called "Ignore double clicks" which, when enabled, will make is so that plugin doesn't react to double clicks, it won't pause/play the video on a double click, the video will remain in its current state (paused/playing).

**Comment by nurupo** [comment]
Say if this works for you and what OS and VLC version you use.

**Comment by gKrager** [comment]
> That's interesting, never expected anyone to actually use the Right Button option. I have added those button choices just because I could and having an option to use Middle Button sounded nice.
> 
> Anyway, I can modify the plugin to prevent the context menu from appearing. I wouldn't be able to properly test it for about a week though, don't have a Windows machine nearby, so releasing this change will have to wait. Meanwhile you can test it yourself. I have pushed the code to [`suppress-context-menu`](https://github.com/nurupo/vlc-pause-click-plugin/tree/suppress-context-menu) branch in case you compile from source, and here are Windows binaries:
> 
> * [vlc-2.1-32bit-win.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/3048265/vlc-2.1-32bit-win.zip)
> * [vlc-2.1-64bit-win.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/3048266/vlc-2.1-64bit-win.zip)
> * [vlc-2.2-32bit-win.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/3048267/vlc-2.2-32bit-win.zip)
> * [vlc-2.2-64bit-win.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/3048268/vlc-2.2-64bit-win.zip)
> * [vlc-3.0-32bit-win.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/3048269/vlc-3.0-32bit-win.zip)
> * [vlc-3.0-64bit-win.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/3048270/vlc-3.0-64bit-win.zip)
> 
> By the way, if you are using Right Button instead of Left Button because you don't like the video pausing and then playing when you double-click to full screen - there is an option called "Ignore double clicks" which, when enabled, will make is so that plugin doesn't react to double clicks, it won't pause/play the video on a double click, the video will remain in its current state (paused/playing).

I got used to pausing the video with the right click from using MPV, I guess it must be weird for some.

So far it's working flawlessly, thank you very much!

OS: Windows 10 64bit
VLC: 3.0.6

**Comment by nurupo** [comment]
Here are pre-release binaries based on the current master branch, if you want to test them. The right click context menu stuff is no longer hard-coded, there are options for it now. You can also re-assign the context menu popup and fullscreen toggle to any mouse button now.

All that's left for the release is make updated Windows VLC screenshots for the README file and create a version tag.

![Screenshot](https://user-images.githubusercontent.com/1855294/56086035-3737a680-5e1c-11e9-99c8-e81a3dcc5db1.png)

[vlc-2.1-32bit-win.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/3076797/vlc-2.1-32bit-win.zip)
[vlc-2.1-64bit-win.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/3076798/vlc-2.1-64bit-win.zip)
[vlc-2.2-32bit-win.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/3076799/vlc-2.2-32bit-win.zip)
[vlc-2.2-64bit-win.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/3076800/vlc-2.2-64bit-win.zip)
[vlc-3.0-32bit-win.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/3076801/vlc-3.0-32bit-win.zip)
[vlc-3.0-64bit-win.zip](https://github.com/nurupo/vlc-pause-click-plugin/files/3076802/vlc-3.0-64bit-win.zip)

**Comment by nurupo** [comment]
Should be addressed by the 2.0.0 release https://github.com/nurupo/vlc-pause-click-plugin/releases/tag/2.0.0
