### ISSUE TITLE
Doesn't work with Video Post Processing Filter and/or Sharpen Filter

### ISSUE THREAD

**Issue by kibafool** [nurupo/vlc-pause-click-plugin#59]
##### Self-troubleshooting

- [X] I have went over the [Troubleshooting section](https://github.com/nurupo/vlc-pause-click-plugin#troubleshooting) and the issue still persists

##### Software

OS: Windows 
VLC version: 3.08
VLC bitness: 64
Plugin version: latest version
Plugin bitness: 64

##### Issue description

Turning on either Video Post Processing Filter or Sharpen Filter causes pause to click to stop working.

**Comment by nurupo** [comment]
Interesting. Did a quick test on Linux with VLC 3.0.8 and the plugin still works with those filters enabled.

Will check on Windows later.

**Comment by nurupo** [comment]
Can't reproduce it.

Tested both 32-bit and 64-bit VLC 3.0.8 on Windows 7.

- 64-bit VLC - crashes whenever Video Post Processing Filter is enabled and its "Post processing quality" setting is set to or above 5. It does so even without vlc-pause-click-plugin installed, so the crash is not related to it. When I set it below 5 then VLC no longer crashes and vlc-pause-click-plugin works fine, even with the Sharpen filter enabled.

- 32-bit VLC - vlc-pause-click-plugin works without any issue with Video Post Processing and/or Sharpen filters. Video Post Processing Filter doesn't cause any crashes either.

---

Could you screenshot the plugin tree in Tools -> Messages -> Modules Tree? You don't have to screenshot the whole thing, just the items under "video output". I wan to see if the order in which `filter "pause_click"`, `filter "sharpen"` and `filter "postproc"` appear in your VLC match what I have.

**Comment by kibafool** [comment]
After doing some testing after your post, it seems that the two filters cause it to stop working when you set your video output to "OpenGL video output for Windows". (Which is the only way I've been able to get Post Processing Quality to be set to 5 or above so far.)

**Comment by kibafool** [comment]
[Screenshot of Modules Tree](https://i.imgur.com/hnmhiXD.png)

**Comment by nurupo** [comment]
Reproduced the issue on Windows, setting the video output to "OpenGL video output for Windows" was the key. Plugin works fine with no extra filters, but stops working with `sharpen` and/or `postproc` enabled - just as reported. Will see what I can do.

It seems to be Windows-specific, the same is not reproducible on Linux (Linux also has an OpenGL video output option).

**Comment by nurupo** [comment]
Took a closer look.

The reason why pause-click functionality doesn't work when `sharpen` and/or `postproc` filters are enabled is because they somehow cause VLC to unload all video filter plugins. `pause_click` is partly a video filter plugin and partly interface, so this causes the video filter part of it to not load. Even `sharpen` and `postproc` video filters themselves are not loaded. You can see that in the modules tree - they are not in the tree, and in the log messages - VLC talks about unloading them. You can also set Sharpen to the max value of 2 and see that the picture doesn't change. Same with the Post Processing settings - nothing changes.

[Here is a screenshot of the module tree](https://user-images.githubusercontent.com/1855294/70684244-7e0fc180-1c73-11ea-8ca1-d1923b486d2a.png) with just `pause_click` enabled - you can see that both video filter and interface parts of  `pause_click` are loaded, pause-click functionality works as expected.

[Here is a screenshot of the module tree](https://user-images.githubusercontent.com/1855294/70684269-98499f80-1c73-11ea-8def-a154dfb2c454.png) with `pause_click`, `sharpen` and `postproc` enabled - you can see that none of the enables video filters are listed, only the interface part of `pause_click` is loaded, which is not enough for the plugin to function.

(You have to play a video file for VLC to load video-related modules and populate the modules tree with them, which is why you see more modules loaded in my screenshots than in your).

Don't think there is anything I can do within my plugin to fix the issue of VLC unloading all video filter plugins when "OpenGL video output for Windows" video output and `sharpen` and/or `postproc` video filters are enabled.
