### ISSUE TITLE
Add margin on area where the plugin operates to avoid play/pause while seeking

### ISSUE THREAD

**Issue by tarun0** [nurupo/vlc-pause-click-plugin#66]
##### Self-troubleshooting

- [x] I have went over the [Troubleshooting section](https://github.com/nurupo/vlc-pause-click-plugin#troubleshooting) and the issue still persists

##### Software

OS: Windows / Linux / macOS : Windows 10
VLC version: 3.0.10
VLC bitness: 64
Plugin version: 3.0
Plugin bitness:  64

##### Issue description
_It's not an issue but feature request_
I'm able to use the plugin and while it works flawlessly, the video pauses many a time while seeking because the mouse pointer is slightly above seekbar (just touching the video area) while clicking. 

I think it'll be better to reduce the clickable area to something like 20-50 pixel above the seekbar (maybe similar margins below the Menu bar? ) or provide such a setting to the user to modify the same.

**Comment by nurupo** [comment]
After a closer look, this feature request is a no go. It doesn't make much sense for the plugin to implement a workaround for user's inability to properly aim their mouse cursor at the seek bar. Many popular players have a seek bar right next to the video image that pauses when clicked on: YouTube's web player, MPC-HC, etc., so it's not something unique to VLC. More so, VLC provides a visual cue of whether a user mouses over a seekbar by displaying a timestamp tooltip, which is hard to miss. Apart from it not making sense to implement in the first place, it would also unnecessarily complicate the already complex plugin (due to having to add exceptions to the double click behavior logic and implementing a sub source submodule). I see no good reason to implement it.
