### ISSUE TITLE
Mac Osx Binaries?

### ISSUE THREAD

**Issue by xenio** [nurupo/vlc-pause-click-plugin#7]
Any chance to have the Mac Osx binaries?
I miss click to pause on VLC.

**Comment by nurupo** [comment]
I don't own a Mac, so I can't really provide such binaries.

I can give you some pointers on how to build the plugin on OS X though.

**Comment by xenio** [comment]
Yes please, I can try to build for mac os.

**Comment by nurupo** [comment]
Since there is no libvlccore available for OS X (at least one that I could find), you would need to build VLC itself with my plugin in its source tree, then get the plugin binary out and use it with your system's VLC.

[This page describes how to build VLC](https://wiki.videolan.org/OSXCompile/). Make sure that the version of VLC  you build matches the version of VLC you want to use the plugin in, i.e. checkout the appropriate git tag matching your installed VLC version after you get VLC source code from the git.

Before building VLC, integrate my plugin into its source tree. To do that, put `pause_click.c` file appropriate for your VLC version (I have two versions of that file in my repository: [vlc-2.1.x](https://github.com/nurupo/vlc-pause-click-plugin/tree/master/vlc-2.1.x) and [vlc-2.2.x+](https://github.com/nurupo/vlc-pause-click-plugin/tree/master/vlc-2.2.x+)) into `modules/video_filter/` and add

```
libpause_click_plugin_la_SOURCES = pause_click.c
libpause_click_plugin_la_CFLAGS = $(AM_CFLAGS)
libpause_click_plugin_la_LIBADD = $(AM_LIBADD)
video_filter_LTLIBRARIES += libpause_click_plugin.la
```

to the `Modules.am` that is located in the same directory.

Then build VLC. You don't have to build a complete VLC, so you can disable some modules that cause your build to fail. All you care is for the plugin to get built, you shouldn't care for VLC you are building. You should get  `libpause_click_plugin.so` or `libpause_click_plugin.dylib` in the end.

**Comment by nurupo** [comment]
That's pretty much how I got those Windows binaries -- cross-compiled VLC 6 times (3 versions, 2 architectures).

**Comment by xenio** [comment]
With your help I did the build for 2.2 version, there is a libpause_click_plugin.dylib in the plugin folder and the option to activate it in the Interface ->  Control Interface -> Play Pause Video on Mouse Click

https://www.dropbox.com/s/nwk1w9vou44sjqk/Screenshot%202015-08-22%2013.40.29.png?dl=0

but when I click on the video nothing happens.
It is not clear for me how to use the file vlc_interface.h, I've did a build without it and also overwriting the original file in vlc/include source with yours, but clicking does nothing.
Any suggestions?
Thanks.

**Comment by nurupo** [comment]
For 2.2 you have to check two checkboxes in options, one in Interface, another somewhere in Video -> Filters, as described in [Usage](https://github.com/nurupo/vlc-pause-click-plugin/tree/master/vlc-2.2.x%2B#usage).

![adfxcvdsfsf](https://cloud.githubusercontent.com/assets/1855294/9425753/9011a5ee-48ea-11e5-87a6-c161935a1e33.png)

 VLC changed a few things in how plugins work in 2.2 version, so it needs two checkboxes to be checked. The Interface one allows the plugin to pause/play currently playing thing and the Video -> Filter allows the plugin to receive mouse click events made on video surface.

You shouldn't use `vlc_interface.h` for anything, it's there just to make Debian/Linux builds work.

**Comment by xenio** [comment]
OMG Thanks, it is working now, I just copied the libpause_click_plugin.dylib from the build 2.2 into my vlc 2.2.2 plugin folder /Applications/VLC.app/Contents/MacOS/plugins
this is the library for Mac Os if you want to share.
https://www.dropbox.com/s/rwc3oaf8x81dt8f/libpause_click_plugin.dylib?dl=0

**Comment by nurupo** [comment]
Would be nice if you could also provide `libpause_click_plugin.dylib` for 2.1.x and 3.0.x :)

**Comment by xenio** [comment]
I am getting some problem building the plugin with 3.x:

There is no Modules.am file on video_filter folder but Makefile.am and if I add your lines to that file I get this: *** No rule to make target `pause_click.c', needed by `libpause_click_plugin_la-pause_click.lo'.  Stop.
Changing libpause_click_plugin_la_SOURCES = pause_click.c to libpause_click_plugin_la_SOURCES = video_filter/pause_click.c build vlc.app without any errors.
I can't build the 2.1 version, I get errors, maybe I am missing some commands.

Binaries for Mac OS VLC 2.2.x and 3.x
https://dl.dropboxusercontent.com/u/1234576/VLC_PauseClick_MacOs.zip

**Comment by nurupo** [comment]
>Binaries for Mac OS VLC 2.2.x and 3.x
>https://dl.dropboxusercontent.com/u/1234576/VLC_PauseClick_MacOs.zip

Thanks, added them to the README file.

>Just a feature request: is it possible to add the PAUSE/PLAY ICON as when you click the pause/play button on full screen?

Sounds like it's something OS X specific, I don't see any pause/play icon in full screen either on Linux or Windows, aside from the regular pause/play button in the control panel (the left bottom button on the screenshot).

![kde-vlc-fullscreen-control-panel](https://cloud.githubusercontent.com/assets/1855294/9455476/88392ab2-4a99-11e5-8d0d-52753d2ebe24.png)

**Comment by xenio** [comment]
The play/pause icon appears only if you press the spacebar.

![screenshot-2015-08-25-10 47 59](https://cloud.githubusercontent.com/assets/153355/9462610/3e450844-4b17-11e5-8ae8-8d1f00e18d2d.jpg)

**Comment by nurupo** [comment]
Oh, I see it now.

What I currently do is pausing/playing current item from the playlist. I looked around VLC API to see if I could send "spacebar pressed" event, which should also make that icon show up, but it looks like only video output plugins can do that and writing one is out of question.

I could draw those pause/play icons myself, that's what video filter plugins can do, but then my drawing might not match the one you see in your interface when pressing the spacebar, since it might be interface-dependent and there are many different interface back-ends for VLC.

**Comment by nurupo** [comment]
>Just a feature request: is it possible to add the PAUSE/PLAY ICON as when you click the pause/play button on full screen?

Just letting you know that I have added this in the latest version of the plugin.
